[package]
name = "cheap-ruler"
version = "0.0.1"
authors = ["Marin Rukavina <marin@shinyshell.net>"]
edition = "2018"

[dependencies]
geo = "^0.13"
num-traits = "^0.2"

[dev-dependencies]
assert_approx_eq = "1.1.0"
